
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 15155
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdministratorGUI
     * @param role
     */
    private final String role_;
    private final String name_;
    private final int authority_;
    public MainGUI(String role ,String name) {
        initComponents();
        role_ = role;
        name_ = name;
        switch (role) {
            case "Administrator":
                docUp.enable(false);
                this.setTitle("管理员界面");
                authority_ = 1;
                break;
            case "Operator":
                userCmd.enable(false);
                this.setTitle("档案管理者界面");
                authority_ = 0;
                break;
            case "Browser":
                userCmd.enable(false);
                authority_ = 0;
                this.setTitle("浏览者界面");
                break;
            default:
                authority_ = 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        userCmd = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        docUp = new javax.swing.JMenuItem();
        docDown = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userCmd.setText("用户管理");

        jMenuItem4.setText("修改用户");
        jMenuItem4.setContentAreaFilled(false);
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        userCmd.add(jMenuItem4);

        jMenuItem5.setText("删除用户");
        jMenuItem5.setContentAreaFilled(false);
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        userCmd.add(jMenuItem5);

        jMenuItem6.setText("新增用户");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        userCmd.add(jMenuItem6);

        jMenuBar1.add(userCmd);

        jMenu4.setText("档案管理");

        docUp.setText("档案上传");
        docUp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        docUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docUpActionPerformed(evt);
            }
        });
        jMenu4.add(docUp);

        docDown.setText("档案下载");
        docDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docDownActionPerformed(evt);
            }
        });
        jMenu4.add(docDown);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("个人信息管理");

        jMenuItem3.setText("个人信息修改");
        jMenuItem3.setSelected(true);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        StartGUI.application.processConnection("MainGUI---UserCmd---DELETE");
        UserCmdGUI.GUI(1);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        StartGUI.application.processConnection("MainGUI---UserCmd---CHANGE");
        UserCmdGUI.GUI(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        StartGUI.application.processConnection("MainGUI---InfoManage---INFOCHANGE");
        InfoManageGUI.GUI(authority_, name_, role_);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void docUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docUpActionPerformed
        // TODO add your handling code here:
        if ("Operator".equals(role_)) {
            StartGUI.application.processConnection("MainGUI---FileManage---UPLOAD");
            FileManageGUI.GUI(role_ , 0, name_);
        }
    }//GEN-LAST:event_docUpActionPerformed

    private void docDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docDownActionPerformed
        // TODO add your handling code here:
        StartGUI.application.processConnection("MainGUI---FileManage---DOWNLOAD");
        FileManageGUI.GUI(role_ , 1, name_);
    }//GEN-LAST:event_docDownActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        StartGUI.application.processConnection("MainGUI---UserCmd---ADD");
        UserCmdGUI.GUI(2);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param role
     * @param name
     */
    public static void GUI(String role ,String name) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainGUI(role, name).setVisible(true);
            }
        });
    }
    
    public boolean isExit() {
//        if (MainGUI.)
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem docDown;
    private javax.swing.JMenuItem docUp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu userCmd;
    // End of variables declaration//GEN-END:variables
}
